### ISSUE TITLE
upgrade failing on fork-exec

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#234]
when testing the upgrade today, I got the following error in the master process:

```
Aug 28 15:48:46 rustyxorp sozu[29413]: 2017-08-28T15:48:46Z        2163626035071621        29413        INFO        MASTER        received LaunchWorker with tag "BLAH"
Aug 28 15:48:46 rustyxorp sozu[29413]: 2017-08-28T15:48:46Z        2163626035248329        29413        INFO        MASTER        launching worker
Aug 28 15:48:46 rustyxorp sozu[29413]: 2017-08-28T15:48:46Z        2163626041147530        29413        INFO        MASTER        worker launched: 18277
Aug 28 15:48:46 rustyxorp sozu[29413]: 2017-08-28T15:48:46Z        2163626041398270        29413        INFO        MASTER        created new worker
Aug 28 15:48:46 rustyxorp sozu[29413]: thread 'main' panicked at 'internal error: entered unreachable code', bin/src/worker.rs:152:6
Aug 28 15:48:47 rustyxorp sozu[29413]: 2017-08-28T15:48:47Z        2163626577797786        29413        INFO        MASTER        worker (BLAH-3) sent: None
```

Why is this code reaching the `unreachable!()` call? https://github.com/sozu-proxy/sozu/blob/2a79ca84c2f74480ab2e7081c503632dfb83ddaf/bin/src/worker.rs#L142-L152

**Comment by BlackYoup** [comment]
I can't reproduce anymore, did you fix it since then ? Upgrades seems to work fine

**Comment by Geal** [comment]
I couldn't reproduce it, but fixed other issues with upgrades in the
meantime. If that one was fixed as a side effect, that's cool :)

Le 10 oct. 2017 11:34 PM, "Arnaud Lefebvre" <notifications@github.com> a
écrit :

**Comment by BlackYoup** [comment]
Just had it again:
```
2017-10-17T14:27:50Z    3385013694120889        6622    DEBUG   MASTER  sozu::command   server accepting socket
2017-10-17T14:27:50Z    3385013717584460        6622    TRACE   MASTER  sozu::command::orders   answer_success for front token FrontToken(0) id LIST-WORKERS-sSF8uw, message "" data Some(
    Workers(
        [
            WorkerInfo {
                id: 0,
                pid: 6647,
                run_state: Running
            }
        ]
    )
)
2017-10-17T14:27:50Z    3385013720477167        6622    INFO    MASTER  received LaunchWorker with tag "BLAH"
2017-10-17T14:27:50Z    3385013720536766        6622    TRACE   MASTER  sozu::worker    parent(6622)
2017-10-17T14:27:50Z    3385013724774438        6622    INFO    MASTER  launching worker
2017-10-17T14:27:50Z    3385013725144763        6622    INFO    MASTER  worker launched: 16855
2017-10-17T14:27:50Z    3385013725343251        6622    TRACE   MASTER  sozu::worker    child(16855):    will spawn a child
thread 'main' panicked at 'internal error: entered unreachable code', src/worker.rs:154:6
2017-10-17T14:27:50Z    3385013726224191        6622    INFO    MASTER  created new worker
2017-10-17T14:27:50Z    3385014233707222        6622    INFO    MASTER  worker (BLAH-1) sent: None
2017-10-17T14:27:53Z    3385017345062799        6647    INFO    TAG-0   pipe back_readable
2017-10-17T14:27:53Z    3385017345142958        6647    DEBUG   TAG-0   sozu_lib::network::protocol::pipe        31f1cbd6-2f88-472e-a9f6-4640cd62bce7    unknown         BACK  [6148914691236517212<-6148914691236517711]: read 3 bytes
```

So it seems like it's not fixed yet and randomly appear :(
It was in debug build

**Comment by Geal** [comment]
could you check the result of the command exec? maybe there's some info
there

**Comment by BlackYoup** [comment]
Oh, so it seems to happen only when the bin/ has been rebuilt.

The fork error is:
2017-10-17T14:57:17Z    390395911884613 23670   INFO    MASTER  launching worker with path Ok("/home/arnaud/Dev/sozu/target/debug/sozu (deleted)")
`2017-10-17T14:47:46Z    3386210210589086        17016   ERROR   MASTER  Fork result: Error { repr: Os { code: 2, message: "No such file or directory" } }`

So it seems like that it doesn't like the fact that the initial `sozu` binary has been deleted
