### ISSUE TITLE
Configuration: panic occurs when a listener doesn't have any applications

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#531]
The panic is (I think) here: https://github.com/sozu-proxy/sozu/blob/f847771480e82c2891ee20a61f2e8025ca761835/lib/src/network/tcp.rs#L967

```
#9  0x00005624bf457a4b in core::panicking::panic ()
#10 0x00005624bf0abc30 in <sozu_lib::network::tcp::ServerConfiguration as sozu_lib::network::ProxyConfiguration<sozu_lib::network::tcp::Client>>::create_client ()
#11 0x00005624bf055752 in sozu_lib::network::proxy::Server::create_client_tcp ()
#12 0x00005624bf056719 in sozu_lib::network::proxy::Server::create_clients ()
#13 0x00005624bf050abc in sozu_lib::network::proxy::Server::run ()
#14 0x00005624befa5d90 in sozu::worker::begin_worker_process ()
#15 0x00005624bef3a72c in sozu::cli::upgrade_worker ()
#16 0x00005624beeec157 in sozu::main ()
#17 0x00005624bef2de23 in std::rt::lang_start::{{closure}} ()
#18 0x00005624bf3fa853 in std::panicking::try::do_call ()
#19 0x00005624bf40e47a in __rust_maybe_catch_panic ()
#20 0x00005624bf3f69a6 in std::rt::lang_start_internal ()
#21 0x00005624beeed2d4 in main ()
```

I only had a listener set to listen on `0.0.0.0:22` without applications using that listener. When I tried to connect to port 22, the panic happened.

The panic should be avoided and an error message should be shown instead. Maybe a warning about "no applications linked to that listener" when sozu finishes loading its configuration would make sense too?

**Comment by BlackYoup** [comment]
Fixed by https://github.com/sozu-proxy/sozu/commit/325a7a884cf938a785b2c8d81c526e038120426c
