### ISSUE TITLE
Panic: unreachable!() triggered in network::tcp::Session::front_hup

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#535]
I got a few panics lately, triggered here: https://github.com/sozu-proxy/sozu/blob/master/lib/src/network/tcp.rs#L189

I have a sozu doing TCP proxying in front of a more regular sozu instance. It's the sozu instance that received the proxied stream that panic'd.

The logs of the sozu instance:
```
Oct 08 01:17:37 exherbo-dedicated sozu[31568]: 2018-10-07T23:17:37Z 23864665624130340 11636 WRK-54 TRACE        sozu_lib::network::server       PROXY   Token(5) got events: Readable                                                         
Oct 08 01:17:37 exherbo-dedicated sozu[31568]: 2018-10-07T23:17:37Z 23864665624307708 11636 WRK-54 TRACE        sozu_lib::network::server       PROXY   Token(10) got events: Readable | Writable | Hup                                       
Oct 08 01:17:37 exherbo-dedicated sozu[31568]: 2018-10-07T23:17:37Z 23864665624325538 11636 WRK-54 TRACE        sozu_lib::network::tcp  token Token(10) got event RW-H                                                                        
Oct 08 01:17:37 exherbo-dedicated sozu[31568]: 2018-10-07T23:17:37Z 23864665624365688 11636 WRK-54 INFO ed1a8d77-610b-4645-a00e-33c7c986118a    unknown 127.0.0.1:15862 -> -    0 0 0 0                                                       
Oct 08 01:17:37 exherbo-dedicated sozu[31568]: thread 'main' panicked at 'internal error: entered unreachable code', lib/src/network/tcp.rs:189:12                                                                                            
Oct 08 01:17:37 exherbo-dedicated sozu[31568]: stack backtrace:
```

The logs of the "sozu-tcp" instance:
```
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665622903834 31592 WRK-00 TRACE        sozu_lib::network::server       PROXY   Token(6) got events: Readable
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665623067152 31592 WRK-00 DEBUG        sozu_lib::network::backends     Connecting sshd -> (V4(127.0.0.1:8022), 1, 0)
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665623249850 31592 WRK-00 TRACE        sozu_lib::network::server       PROXY   Token(18) got events: Readable | Writable | Hup
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665623268720 31592 WRK-00 TRACE        sozu_lib::network::tcp  token Token(18) got event RW-H
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665623295579 31592 WRK-00 INFO 539c3976-c0b0-4f53-8a63-407c062523f7    sshd    124.158.13.136:49990 -> 127.0.0.1:8022  0 0 0 0
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665623308729 31592 WRK-00 TRACE        sozu_lib::network::server       session[SessionToken(18) -> Token(18)] got events Readable | Writable | Hup and returned order
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665623385268 31592 WRK-00 TRACE        sozu_lib::network::server       PROXY   Token(17) got events: Writable
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665961726993 31592 WRK-00 TRACE        sozu_lib::network::server       PROXY   Token(9) got events: Readable | Writable | Hup
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665961758452 31592 WRK-00 TRACE        sozu_lib::network::tcp  token Token(9) got event RW-H
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665961774492 31592 WRK-00 TRACE        sozu_lib::network::tcp  PROXY   f90999cb-bfef-4a63-b8a8-08e9a9e0b88c    https    Token(10) Readiness { interest: R-EH, readines
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665961792012 31592 WRK-00 TRACE        sozu_lib::network::protocol::pipe       pipe back_readable
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665961807852 31592 WRK-00 DEBUG        sozu_lib::network::protocol::pipe       492ef95c-3fb5-4e2c-94e6-f44a57fdc77a    unknown         BACK  [10<-9]: read 0 bytes
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665961837831 31592 WRK-00 INFO f90999cb-bfef-4a63-b8a8-08e9a9e0b88c    https   62.210.85.98:13510 -> 127.0.0.1:8443    4517392 0 84701724 148327
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864665961852221 31592 WRK-00 TRACE        sozu_lib::network::server       session[SessionToken(9) -> Token(9)] got events Readable | Writable | Hup and returned order Cl
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029690872 31592 WRK-00 TRACE        sozu_lib::network::server       PROXY   Token(16) got events: Readable | Writable
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029740052 31592 WRK-00 TRACE        sozu_lib::network::tcp  token Token(16) got event RW--
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029758211 31592 WRK-00 TRACE        sozu_lib::network::tcp  PROXY   47c7e785-aa44-4b12-a955-6f42e457d2d1    sshd     Token(16) Readiness { interest: R-EH, readines
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029777711 31592 WRK-00 TRACE        sozu_lib::network::protocol::pipe       pipe readable
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029800561 31592 WRK-00 DEBUG        sozu_lib::network::protocol::pipe       d2f01e6b-6db6-46a2-8fcb-6b57b2e13d1e    unknown         FRONT [Token(16)]: read 648 byt
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029821191 31592 WRK-00 TRACE        sozu_lib::network::tcp  front readable  interpreting session order Continue
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029834501 31592 WRK-00 TRACE        sozu_lib::network::tcp  PROXY   47c7e785-aa44-4b12-a955-6f42e457d2d1    sshd     Token(16) Readiness { interest: R-EH, readines
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029849490 31592 WRK-00 TRACE        sozu_lib::network::protocol::pipe       pipe back_writable
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029922610 31592 WRK-00 DEBUG        sozu_lib::network::protocol::pipe       d2f01e6b-6db6-46a2-8fcb-6b57b2e13d1e    unknown         BACK [16->15]: wrote 648 bytes
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029940189 31592 WRK-00 TRACE        sozu_lib::network::tcp  PROXY   47c7e785-aa44-4b12-a955-6f42e457d2d1    sshd     Token(16) Readiness { interest: R-EH, readines
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029954899 31592 WRK-00 TRACE        sozu_lib::network::protocol::pipe       pipe back_writable
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029966429 31592 WRK-00 TRACE        sozu_lib::network::tcp  PROXY   47c7e785-aa44-4b12-a955-6f42e457d2d1    sshd     Token(16) Readiness { interest: R-EH, readines
Oct 08 01:17:37 exherbo-dedicated sozu[31578]: 2018-10-07T23:17:37Z 23864666029981249 31592 WRK-00 TRACE        sozu_lib::network::server       session[SessionToken(16) -> Token(16)] got events Readable | Writable and returned order Continue
```

GDB stacktrace:
```
#6  0x000055e0919a4826 in std::panicking::begin_panic ()
#7  0x000055e091a10a50 in <sozu_lib::network::tcp::Session as sozu_lib::network::ProxySession>::ready ()
#8  0x000055e0919c0836 in sozu_lib::network::server::Server::ready ()
#9  0x000055e0919b9ff9 in sozu_lib::network::server::Server::run ()
#10 0x000055e09190f2f0 in sozu::worker::begin_worker_process ()
#11 0x000055e0918a3c8c in sozu::cli::upgrade_worker ()
#12 0x000055e0918556b7 in sozu::main ()
#13 0x000055e091897383 in std::rt::lang_start::{{closure}} ()
#14 0x000055e091d64313 in std::panicking::try::do_call ()
#15 0x000055e091d77f3a in __rust_maybe_catch_panic ()
#16 0x000055e091d60466 in std::rt::lang_start_internal ()
#17 0x000055e091856834 in main ()
```
The lines don't match but I guess the `front_hup()` method gets inlined.

I'm not sure which triggered this but I got 5 of those panics in the last 6 hours.

I can share the configuration if needed, I just need to clean it up a bit before.. I'm also pretty sure that I don't run the 0.9 version but more likely this commit: https://github.com/sozu-proxy/sozu/commit/9f63214e142ea13077e2978d098ca19ffd599266

**Comment by BlackYoup** [comment]
The linked pull request fixed it.
