### ISSUE TITLE
ProxyProtocol: gen_proxy_protocol_header panic: frontend address should be available

### ISSUE THREAD

**Issue by BlackYoup** [sozu-proxy/sozu#548]
Stack trace:
```
#8  0x00005578ed61a3a3 in core::panicking::panic_fmt ()
#9  0x00005578ed32c539 in core::result::unwrap_failed (msg=..., error=...) at /var/tmp/paludis/build/dev-lang-rust-1.27.1/work/rustc-1.27.1-src/src/libcore/macros.rs:26
#10 0x00005578ed337b56 in <core::result::Result<T, E>>::expect (msg=..., self=...) at /var/tmp/paludis/build/dev-lang-rust-1.27.1/work/rustc-1.27.1-src/src/libcore/result.rs:809
#11 <sozu_lib::network::protocol::proxy_protocol::send::SendProxyProtocol<Front>>::gen_proxy_protocol_header (self=0x7f28d1ea2840) at lib/src/network/protocol/proxy_protocol/send.rs:126
#12 <sozu_lib::network::protocol::proxy_protocol::send::SendProxyProtocol<Front>>::set_back_connected (self=0x7f28d1ea2840, status=<optimized out>) at lib/src/network/protocol/proxy_protocol/send.rs:112
#13 0x00005578ed26fd6e in sozu_lib::network::tcp::Session::set_back_connected (self=<optimized out>, status=sozu_lib::network::BackendConnectionStatus::Connected) at lib/src/network/tcp.rs:395
#14 <sozu_lib::network::tcp::Session as sozu_lib::network::ProxySession>::ready (self=0x7f28d1ea2718) at lib/src/network/tcp.rs:537
#15 0x00005578ed1fc316 in sozu_lib::network::server::Server::ready (self=0x7ffd1b2d4d00, token=..., events=...) at lib/src/network/server.rs:1196
#16 0x00005578ed1f56db in sozu_lib::network::server::Server::run (self=0x7ffd1b2d4d00) at lib/src/network/server.rs:390
#17 0x00005578ed082c2a in sozu::worker::begin_worker_process (fd=<optimized out>, scm=<optimized out>, configuration_state_fd=<optimized out>, id=<optimized out>, command_buffer_size=<optimized out>, max_command_buffer_size=<optimized out>)
    at bin/src/worker.rs:98
#18 0x00005578ed0c9fec in sozu::cli::upgrade_worker::{{closure}} (worker_matches=<optimized out>) at bin/src/cli.rs:92
#19 <core::option::Option<T>>::and_then (self=..., f=...) at /var/tmp/paludis/build/dev-lang-rust-1.27.1/work/rustc-1.27.1-src/src/libcore/option.rs:612
#20 sozu::cli::upgrade_worker (matches=<optimized out>) at bin/src/cli.rs:84
#21 0x00005578ed0b41f2 in sozu::main () at bin/src/main.rs:59
```

Logs:
```
Oct 16 09:15:30 par-cleverapps-adc-n3 sozu[20043]: thread 'main' panicked at 'frontend address should be available: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', libcore/result.rs:945:5
Oct 16 09:15:30 par-cleverapps-adc-n3 sozu[20043]: stack backtrace:
```

**Comment by Geal** [comment]
please test with the PR

**Comment by Geal** [comment]
@BlackYoup is it still happening?

**Comment by BlackYoup** [comment]
No, the pull request has fixed this.
