### ISSUE TITLE
BorrowMutError on 0.14 branch

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#711]
Just saw that on my server, a double borrow happens when closing sessions because a timeout triggered:

```
thread 'main' panicked at 'already borrowed: BorrowMutError', lib/src/http.rs:774:32                                                 
stack backtrace:                                                                                                                     
   0:     0x560e2f3dcc33 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7                                         
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libun
wind.rs:90:5                                                                                                                         
   1:     0x560e2f3dcc33 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc                                     
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.r
s:66:5                                                                                                                               
   2:     0x560e2f3dcc33 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5                                                 
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5       
   3:     0x560e2f3dcc33 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618      
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22      
   4:     0x560e2f0c70dc - core::fmt::write::h88012e1f01caeebf                                                                       
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17                
   5:     0x560e2f3dab34 - std::io::Write::write_fmt::h360fa85b30182555                                                              
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15                  
   6:     0x560e2f3dbdab - std::sys_common::backtrace::_print::ha1f00492f406a015                                                     
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5       
   7:     0x560e2f3dbdab - std::sys_common::backtrace::print::hd54561b13feb6af3                                                      
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9       
   8:     0x560e2f3dbdab - std::panicking::default_hook::{{closure}}::h84fe124cd0864662                                              
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50                
   9:     0x560e2f3dafbf - std::panicking::default_hook::h5a8e74a76ce290a7                                                           
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9                 
  10:     0x560e2f3da9f0 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91                                                   
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17                
  11:     0x560e2f3f4bd8 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7                                       
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13                
  12:     0x560e2f3f4b4c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e                                 
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18     
  13:     0x560e2f3f4afd - rust_begin_unwind                                                                                         
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5                 
  14:     0x560e2edfb9d0 - core::panicking::panic_fmt::h12a3a3c256485fca                                                             
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14                
  15:     0x560e2edfbd02 - core::result::unwrap_failed::h2d8d0952e3250de9                                                            
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5                  
  16:     0x560e2f270613 - core::result::Result<T,E>::expect::hd33b40724693ee70                                                      
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1241:23                 
  17:     0x560e2f270613 - core::cell::RefCell<T>::borrow_mut::h7d535b52bf2c546d                                                     
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/cell.rs:920:9                     
  18:     0x560e2f270613 - sozu_lib::http::Session::close_backend::h0e2b7d29c58a805b                                                 
                               at /home/geal/dev/sozu/lib/src/http.rs:774:17                                                         
  19:     0x560e2f26e74e - <sozu_lib::http::Session as sozu_lib::ProxySession>::close::hb7ab9449c76e1657                             
                               at /home/geal/dev/sozu/lib/src/http.rs:1142:9                                                         
  20:     0x560e2f271902 - <sozu_lib::http::Session as sozu_lib::ProxySession>::timeout::h012215ae3e47d8a0                           
                               at /home/geal/dev/sozu/lib/src/http.rs:1196:13                                                        
  21:     0x560e2f2c6618 - sozu_lib::server::Server::timeout::hbb3b0618d1e6bf55                                                      
                               at /home/geal/dev/sozu/lib/src/server.rs:1667:13                                                      
  22:     0x560e2f2b8d09 - sozu_lib::server::Server::run::hccd9d47f9d792f05                                                          
                               at /home/geal/dev/sozu/lib/src/server.rs:640:25                                                       
```

**Comment by Geal** [comment]
fixed in c2ad84ab48
